# OpenSincera Data Sync Script
# Run this periodically to refresh local data cache

$API_BASE = "https://open.sincera.io/api"
$API_KEY = "c54dc3e17898500ecab43e76ba24bf"
$DATA_DIR = "$PSScriptRoot\data"

# Create data directory if it doesn't exist
if (!(Test-Path $DATA_DIR)) {
    New-Item -ItemType Directory -Path $DATA_DIR | Out-Null
}

$headers = @{
    "Authorization" = "Bearer $API_KEY"
    "Content-Type" = "application/json"
}

# Use UTF8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding $false

Write-Host "OpenSincera Data Sync" -ForegroundColor Cyan
Write-Host "=====================" -ForegroundColor Cyan

# Fetch ecosystem data
Write-Host "`nFetching ecosystem data..." -ForegroundColor Yellow
try {
    $ecosystem = Invoke-RestMethod -Uri "$API_BASE/ecosystem" -Headers $headers -Method Get
    $json = $ecosystem | ConvertTo-Json -Depth 10
    [System.IO.File]::WriteAllText("$DATA_DIR\ecosystem.json", $json, $utf8NoBom)
    Write-Host "  Saved ecosystem.json" -ForegroundColor Green
} catch {
    Write-Host "  Failed to fetch ecosystem: $_" -ForegroundColor Red
}

# Fetch popular publishers (you can customize this list)
$publisherIds = @(1, 2, 3, 4, 5, 10, 20, 50, 100)
$publishers = @{}

Write-Host "`nFetching publisher data..." -ForegroundColor Yellow
foreach ($id in $publisherIds) {
    try {
        $pub = Invoke-RestMethod -Uri "$API_BASE/publishers?id=$id" -Headers $headers -Method Get
        $publishers[$id.ToString()] = $pub
        
        # Also index by domain if available
        if ($pub.domain) {
            $publishers[$pub.domain] = $pub
        }
        
        Write-Host "  Fetched publisher ID $id" -ForegroundColor Green
        Start-Sleep -Milliseconds 200  # Rate limiting
    } catch {
        Write-Host "  Failed to fetch publisher $id" -ForegroundColor Red
    }
}

# Save publishers index
$json = $publishers | ConvertTo-Json -Depth 10
[System.IO.File]::WriteAllText("$DATA_DIR\publishers.json", $json, $utf8NoBom)
Write-Host "`nSaved publishers.json with $($publishers.Count) entries" -ForegroundColor Green

# Create metadata file
$metadata = @{
    lastUpdated = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    publisherCount = $publishers.Count
    source = "OpenSincera API"
}
$json = $metadata | ConvertTo-Json
[System.IO.File]::WriteAllText("$DATA_DIR\metadata.json", $json, $utf8NoBom)

# Generate data.js for direct browser use (no fetch/server needed)
Write-Host "`nGenerating data.js for static loading..." -ForegroundColor Yellow
$publishersJson = [System.IO.File]::ReadAllText("$DATA_DIR\publishers.json", $utf8NoBom)
$ecosystemJson = [System.IO.File]::ReadAllText("$DATA_DIR\ecosystem.json", $utf8NoBom)
$dataJs = @"
// Auto-generated by sync-data.ps1 — do not edit manually
var PUBLISHERS_DATA = $publishersJson;
var ECOSYSTEM_DATA = $ecosystemJson;
"@
[System.IO.File]::WriteAllText("$DATA_DIR\data.js", $dataJs, $utf8NoBom)
Write-Host "  Saved data.js" -ForegroundColor Green

Write-Host "`nSync complete!" -ForegroundColor Cyan
Write-Host "Data saved to: $DATA_DIR" -ForegroundColor Cyan
